version: '3'

networks:
  db:

volumes:
  db:

services:

  db:
    hostname: ambit-db
    image: ideaconsult/ambit-db:latest
    restart: unless-stopped
    env_file:
      - ambit-config.env
    volumes:
      - db:/var/lib/mysql
      - ./data_import:/opt/ambit/data_import
    networks:
      - db

  api-calibrate:
    hostname: ambit-api-calibrate
    image: ideaconsult/ambit-api:latest
    restart: unless-stopped
    env_file:
      - ambit-config.env
    environment:
      - "AMBIT_DATABASE=calibrate"
    depends_on:
      - db
    networks:
      - db
    ports:
      - '127.0.0.1:8082:8080'

  api-nanoreg1:
    hostname: ambit-api-nanoreg1
    image: ideaconsult/ambit-api:latest
    restart: unless-stopped
    env_file:
      - ambit-config.env
    environment:
      - "AMBIT_DATABASE=nanoreg1"
    depends_on:
      - db
    networks:
      - db
    ports:
      - '127.0.0.1:8080:8080'

  api-nanoreg2:
    hostname: ambit-api-nanoreg2
    image: ideaconsult/ambit-api:latest
    restart: unless-stopped
    env_file:
      - ambit-config.env
    environment:
      - "AMBIT_DATABASE=nanoreg2"
    depends_on:
      - db
    networks:
      - db
    ports:
      - '127.0.0.1:8081:8080'
